### ISSUE TITLE
Cannot install/update Python Script

### ISSUE THREAD

**Issue by SeLLeRoNe** [hacs/integration#978]
Hi there,
I am using latest Stable HA (0.105.5) with latest HACS (0.21.5) and I was trying to update the "Data Countdown" Python Script.

Once I confirm the update, it start to show the "circle" as if it is doing something, but once it finishes it still show me the "Update" button as if it was not updated.

Doing a diff show the file to be different, but I am not sure which version is being downloaded (based on what HACS say it should be the 3.1.

I have also tried to remove the plugin and re-installing from scratch but same result happen (it actually result not to be installed at all now).

I did grab some DEBUG logging from startup to my install attempt, here they are:
```
2020-02-20 11:08:41 DEBUG (MainThread) [hacs] Configuration type: yaml
2020-02-20 11:08:41 INFO (MainThread) [hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 0.21.5
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-02-20 11:08:41 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Checking repository.
2020-02-20 11:08:45 INFO (MainThread) [hacs.repository.integration.hacs.integration] Registration complete
2020-02-20 11:08:45 INFO (MainThread) [hacs.data] Restore started
2020-02-20 11:08:45 INFO (MainThread) [hacs.data] Restore done
2020-02-20 11:08:45 WARNING (MainThread) [hacs] Configuration option 'python_script' is deprecated and you should remove it from your configuration, HACS will know if you use 'python_script' in your Home Assistant configuration, this option will be removed in a future release.
2020-02-20 11:08:45 WARNING (MainThread) [hacs] Configuration option 'theme' is deprecated and you should remove it from your configuration, HACS will know if you use 'theme' in your Home Assistant configuration, this option will be removed in a future release.
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] appdaemon_path: appdaemon/apps/
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] appdaemon: False
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] config_type: yaml
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] debug: False
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] dev: False
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] frontend_mode: Table
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] frontend_compact: True
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] onboarding_done: True
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] plugin_path: www/community/
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] python_script_path: python_scripts/
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] python_script: False
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] sidepanel_icon: hacs:hacs
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] sidepanel_title: HACS
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] theme_path: themes/
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] theme: False
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] country: ALL
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] experimental: True
2020-02-20 11:08:45 DEBUG (MainThread) [hacs.configuration] release_limit: 5
2020-02-20 11:09:04 DEBUG (MainThread) [hacs] 4586
2020-02-20 11:09:04 DEBUG (MainThread) [hacs] 2020-02-20 10:48:24
2020-02-20 11:09:05 INFO (MainThread) [hacs] Loading known repositories
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.factory] No tasks to execute
2020-02-20 11:09:17 DEBUG (MainThread) [hacs] Starting recuring background task for installed repositories
2020-02-20 11:09:17 DEBUG (MainThread) [hacs] 4567
2020-02-20 11:09:17 DEBUG (MainThread) [hacs] 2020-02-20 10:48:24
2020-02-20 11:09:17 INFO (MainThread) [hacs.factory] Processing 45 tasks
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.integration.custom-components.places] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.vertical-stack-in-card] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.dual-gauge-card] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-slider-entity-row] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.surveillance-card] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.kalkih.mini-media-player] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-fold-entity-row] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.kalkih.mini-graph-card] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-layout-card] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.integration.thomasloven.hass-fontawesome] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.dnguyen800.air-visual-card] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.integration.kalanda.homeassistant-aemet-sensor] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.secondaryinfo-entity-row] Getting repository information
2020-02-20 11:09:17 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-card-tools] Getting repository information
2020-02-20 11:09:28 DEBUG (MainThread) [hacs.repository.plugin.ljmerza.calendar-card] Getting repository information
2020-02-20 11:09:28 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.bar-card] Getting repository information
2020-02-20 11:09:28 DEBUG (MainThread) [hacs.repository.integration.rgruebel.ha_zigbee2mqtt_networkmap] Getting repository information
2020-02-20 11:09:28 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-auto-entities] Getting repository information
2020-02-20 11:09:28 DEBUG (MainThread) [hacs.repository.plugin.atomic7777.atomic_calendar] Getting repository information
2020-02-20 11:09:28 DEBUG (MainThread) [hacs.repository.plugin.ljmerza.github-card] Getting repository information
2020-02-20 11:09:29 DEBUG (MainThread) [hacs.repository.integration.custom-components.youtube] Getting repository information
2020-02-20 11:09:29 DEBUG (MainThread) [hacs.repository.plugin.iantrich.config-template-card] Getting repository information
2020-02-20 11:09:29 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.spotify-card] Getting repository information
2020-02-20 11:09:30 DEBUG (MainThread) [hacs.repository.plugin.mishaaq.sun-card] Getting repository information
2020-02-20 11:09:30 DEBUG (MainThread) [hacs.repository.plugin.benct.lovelace-multiple-entity-row] Getting repository information
2020-02-20 11:09:30 DEBUG (MainThread) [hacs.repository.integration.custom-components.breaking_changes] Getting repository information
2020-02-20 11:09:30 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.decluttering-card] Getting repository information
2020-02-20 11:09:30 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-card-mod] Getting repository information
2020-02-20 11:09:30 DEBUG (MainThread) [hacs.repository.integration.pnbruckner.ha-illuminance] Getting repository information
2020-02-20 11:09:31 DEBUG (MainThread) [hacs.template] 'states' is undefined
2020-02-20 11:09:38 DEBUG (MainThread) [hacs.repository.integration.pnbruckner.ha-sun2] Getting repository information
2020-02-20 11:09:38 DEBUG (MainThread) [hacs.repository.integration.thomasloven.hass-browser_mod] Getting repository information
2020-02-20 11:09:39 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.favicon-counter] Getting repository information
2020-02-20 11:09:39 DEBUG (MainThread) [hacs.repository.plugin.postlund.search-card] Getting repository information
2020-02-20 11:09:40 DEBUG (MainThread) [hacs.repository.plugin.azuwis.zigbee2mqtt-networkmap] Getting repository information
2020-02-20 11:09:40 DEBUG (MainThread) [hacs.repository.integration.thomasloven.hass-favicon] Getting repository information
2020-02-20 11:09:40 DEBUG (MainThread) [hacs.repository.integration.custom-components.ups] Getting repository information
2020-02-20 11:09:40 DEBUG (MainThread) [hacs.repository.plugin.bokub.rgb-light-card] Getting repository information
2020-02-20 11:09:40 DEBUG (MainThread) [hacs.repository.plugin.iantrich.restriction-card] Getting repository information
2020-02-20 11:09:40 DEBUG (MainThread) [hacs.repository.plugin.maykar.custom-header] Getting repository information
2020-02-20 11:09:40 DEBUG (MainThread) [hacs.repository.plugin.thomasloven.lovelace-template-entity-row] Getting repository information
2020-02-20 11:09:40 DEBUG (MainThread) [hacs.repository.integration.kodi1.meteoalarm] Getting repository information
2020-02-20 11:09:41 DEBUG (MainThread) [hacs.repository.theme.JuanMTech.google_dark_theme] Getting repository information
2020-02-20 11:09:42 DEBUG (MainThread) [hacs.repository.integration.Armaell.home-assistant-custom-icons-loader] Getting repository information
2020-02-20 11:09:42 DEBUG (MainThread) [hacs.repository.integration.amelchio.logbook_cache] Getting repository information
2020-02-20 11:09:43 DEBUG (MainThread) [hacs.template] 'now' is undefined
2020-02-20 11:09:44 DEBUG (MainThread) [hacs.template] 'trigger' is undefined
2020-02-20 11:09:44 DEBUG (MainThread) [hacs.template] 'states' is undefined
2020-02-20 11:09:53 INFO (MainThread) [hacs.factory] Task processing of 45 tasks completed in 36 seconds
2020-02-20 11:09:53 DEBUG (MainThread) [hacs.data] Saving data
2020-02-20 11:09:53 DEBUG (MainThread) [hacs] Recuring background task for installed repositories done
2020-02-20 11:09:53 DEBUG (MainThread) [hacs.data] Saving data
2020-02-20 11:09:57 DEBUG (MainThread) [hacs] Running set_state for mf-social/ps-date-countdown
2020-02-20 11:09:57 DEBUG (MainThread) [hacs.data] Saving data
2020-02-20 11:09:57 DEBUG (MainThread) [hacs] Running update for mf-social/ps-date-countdown
2020-02-20 11:09:57 DEBUG (MainThread) [hacs.repository.python_script.mf-social.ps-date-countdown] Getting repository information
2020-02-20 11:10:01 DEBUG (MainThread) [hacs.template] 'states' is undefined
2020-02-20 11:10:02 DEBUG (MainThread) [hacs.data] Saving data
2020-02-20 11:10:06 DEBUG (MainThread) [hacs] Running set_state for mf-social/ps-date-countdown
2020-02-20 11:10:06 DEBUG (MainThread) [hacs.data] Saving data
2020-02-20 11:10:06 DEBUG (MainThread) [hacs] Running install for mf-social/ps-date-countdown
2020-02-20 11:10:06 DEBUG (MainThread) [hacs.repository.python_script.mf-social.ps-date-countdown] Getting repository information
2020-02-20 11:10:12 DEBUG (MainThread) [hacs.template] 'states' is undefined
2020-02-20 11:10:13 ERROR (MainThread) [hacs.repository.python_script.mf-social.ps-date-countdown] Download was not complete [No content to download]
2020-02-20 11:10:13 DEBUG (MainThread) [hacs.data] Saving data
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving lovelace-layout-card/layout-card.js from /home/ha/.homeassistant/www/community/lovelace-layout-card/layout-card.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js from /home/ha/.homeassistant/www/community/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving config-template-card/config-template-card.js from /home/ha/.homeassistant/www/community/config-template-card/config-template-card.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving mini-media-player/mini-media-player-bundle.js from /home/ha/.homeassistant/www/community/mini-media-player/mini-media-player-bundle.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving atomic_calendar/atomic_calendar.js from /home/ha/.homeassistant/www/community/atomic_calendar/atomic_calendar.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving mini-graph-card/mini-graph-card-bundle.js from /home/ha/.homeassistant/www/community/mini-graph-card/mini-graph-card-bundle.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving custom-header/custom-header.js from /home/ha/.homeassistant/www/community/custom-header/custom-header.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving sun-card/sun-card.js from /home/ha/.homeassistant/www/community/sun-card/sun-card.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving surveillance-card/surveillance-card.js from /home/ha/.homeassistant/www/community/surveillance-card/surveillance-card.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving search-card/search-card.js from /home/ha/.homeassistant/www/community/search-card/search-card.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving spotify-card/spotify-card.js from /home/ha/.homeassistant/www/community/spotify-card/spotify-card.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving lovelace-card-tools/card-tools.js from /home/ha/.homeassistant/www/community/lovelace-card-tools/card-tools.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving restriction-card/restriction-card.js from /home/ha/.homeassistant/www/community/restriction-card/restriction-card.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving lovelace-fold-entity-row/fold-entity-row.js from /home/ha/.homeassistant/www/community/lovelace-fold-entity-row/fold-entity-row.js.gz
2020-02-20 11:10:14 DEBUG (MainThread) [hacs] Serving lovelace-auto-entities/auto-entities.js from /home/ha/.homeassistant/www/community/lovelace-auto-entities/auto-entities.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving decluttering-card/decluttering-card.js from /home/ha/.homeassistant/www/community/decluttering-card/decluttering-card.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving lovelace-template-entity-row/template-entity-row.js from /home/ha/.homeassistant/www/community/lovelace-template-entity-row/template-entity-row.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving dual-gauge-card/dual-gauge-card.js from /home/ha/.homeassistant/www/community/dual-gauge-card/dual-gauge-card.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving lovelace-card-mod/card-mod.js from /home/ha/.homeassistant/www/community/lovelace-card-mod/card-mod.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving lovelace-slider-entity-row/slider-entity-row.js from /home/ha/.homeassistant/www/community/lovelace-slider-entity-row/slider-entity-row.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving secondaryinfo-entity-row/secondaryinfo-entity-row.js from /home/ha/.homeassistant/www/community/secondaryinfo-entity-row/secondaryinfo-entity-row.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving vertical-stack-in-card/vertical-stack-in-card.js from /home/ha/.homeassistant/www/community/vertical-stack-in-card/vertical-stack-in-card.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving bar-card/bar-card.js from /home/ha/.homeassistant/www/community/bar-card/bar-card.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving calendar-card/calendar-card.js from /home/ha/.homeassistant/www/community/calendar-card/calendar-card.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving favicon-counter/favicon-counter.js from /home/ha/.homeassistant/www/community/favicon-counter/favicon-counter.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving lovelace-multiple-entity-row/multiple-entity-row.js from /home/ha/.homeassistant/www/community/lovelace-multiple-entity-row/multiple-entity-row.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving air-visual-card/air-visual-card.js from /home/ha/.homeassistant/www/community/air-visual-card/air-visual-card.js.gz
2020-02-20 11:10:15 DEBUG (MainThread) [hacs] Serving github-card/github-card.js from /home/ha/.homeassistant/www/community/github-card/github-card.js.gz
2020-02-20 11:10:15 ERROR (MainThread) [hacs] Tried to serve up '/home/ha/.homeassistant/www/community/rgb-light-card/card.js' but it does not exist
```

**Comment by ludeeus** [comment]
That is not the same @Krocko 
Both are fixed in master, and will be a part of the next release.

**Comment by SeLLeRoNe** [comment]
Hi @ludeeus ,
I did update HACS yesterday but the problem persist, same behaviour and same message (as per @Krocko screenshot.
